alias gcd=". ~/code/timer/gcd"
alias gwd="~/code/timer/set_cwd"
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit --all'
alias gd='git diff'
alias gp='git push'
alias gpl='git pull'
alias gs='git status -sb'
alias vi='vim'
alias v='vim'
alias vip='vim -p'
alias i='irb -r irb/completion'
alias r='ruby'
alias e='elixir'
alias gshead="gs |head -n 1 |awk '{ print \$2 }'"
alias tt="~/code/time_tracker/bin/time_tracker add_entry"
alias trl="~/code/time_tracker/bin/time_report last_day"
alias ll='ls -al'
alias l='ls'
alias va='vagrant'
alias vs='vagrant ssh || vagrant up ; vagrant ssh'
alias vu='vagrant up'
alias vh='vagrant halt'
alias pry='echo "require pry to activate, binding.pry for waypoint" ; pry'
